<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>osu_rx</RootNamespace>
    <AssemblyName>osu!rx</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OsuParsers" Version="1.6.5" />
    <PackageReference Include="SimpleIniConfig" Version="1.0.1" />
    <PackageReference Include="InputSimulator" Version="1.0.4" />
  </ItemGroup>
</Project>
